apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    env:
      - name: ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: accesskey
            key: password
      - name: SPECIAL_LEVEL_KEY
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: special.how
      - name: SPECIAL_TYPE_KEY
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: special.type
    volumeMounts:
    - name: secrets
      mountPath: "/etc/secrets"
      readOnly: true
    - name: config-volume
      mountPath: "/etc/config"
      readOnly: true
  volumes:
  - name: secrets
    secret:
      secretName: accesskey
  - name: config-volume
    configMap:
      name: special-config
  restartPolicy: Always
