#!/usr/bin/env bash

#Choosing the default gateway interface
INET_INTERFACE=`netstat -rn | head -3 | tail -1 | awk '{print $8}'`
#Install directory by default
INSTALL_DIR="/opt/qk8s"
#Kubernetes version (see https://github.com/kubernetes/kubernetes/releases)
K8S_VERSION="v1.2.3"
K8S_API_PORT="8080"
K8S_DNS_IP="10.0.0.10"
K8S_HOSTNAME=`/sbin/ifconfig $INET_INTERFACE | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'`


function command_exists() {
        if [ `which "$1"` ]; then
		echo "INFO - found $1 command"
	else
		if [ "$1" == "kubectl" ]; then
			read -r -p "Kubectl not found. Do want me to install it on $INSTALL_DIR/bin? [Y/n] " response
			case $response in
				[yY][eE][sS]|[yY])
					if [ "$(uname)" == "Darwin" ]; then
						echo "INFO - Downloading kubectl into $INSTALL_DIR/bin/kubectl"
						curl -s -L -o $INSTALL_DIR/bin/kubectl -z $INSTALL_DIR/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$K8S_VERSION/bin/darwin/amd64/kubectl && chmod 755 $INSTALL_DIR/bin/kubectl
						echo "WARNING - Remember to add $INSTALL_DIR/bin/kubectl to your \$PATH env variable"
					elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
						echo "INFO - Downloading kubectl into $INSTALL_DIR/bin/kubectl"
						curl -s -L -o $INSTALL_DIR/bin/kubectl -z $INSTALL_DIR/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$K8S_VERSION/bin/linux/amd64/kubectl && chmod 755 $INSTALL_DIR/bin/kubectl
						echo "WARNING - Remember to add $INSTALL_DIR/bin/kubectl to your \$PATH env variable"
					fi
					;;
				*)
					echo "ERROR - $1 is required but is not installed. Aborting."
					exit 2
				        ;;
			esac
		else
			echo "ERROR - $1 is required but is not installed. Aborting."
			exit 2
		fi
	fi
}

function check_system {
	echo "INFO - Checking system requirements"
	if [ $INSTALL_DIR/bin/kubectl cluster-info 2> /dev/null ]; then
        	echo "ERROR - kubectl is already configured to use an existing cluster"
	        exit 2
    	fi
	#Checking if docker command exists
	command_exists docker
	command_exists kubectl

	#Creating install directories
	echo "INFO - Creating dirs"
	mkdir -p $INSTALL_DIR/{bin,etc/kubernetes/manifests,logs,run,kubelet}
}

function download_kubelet {
	echo "INFO - Downloading kubelet binary version $K8S_VERSION"
	curl -s -L -o $INSTALL_DIR/bin/kubelet -z $INSTALL_DIR/bin/kubelet https://storage.googleapis.com/kubernetes-release/release/$K8S_VERSION/bin/linux/amd64/kubelet && chmod 755 $INSTALL_DIR/bin/kubelet
}

function copy_kubelet_manifests {
	echo "INFO - Copying basic kubernetes manifests"
	#cp -Rpf ./manifests/* $INSTALL_DIR/etc/kubernetes/manifests/
	for file in `ls ./manifests` ; do
		cat ./manifests/$file | \
		sed "s/\${K8S_VERSION}/${K8S_VERSION}/" | \
		sed "s/\${K8S_HOSTNAME}/${K8S_HOSTNAME}/" > $INSTALL_DIR/etc/kubernetes/manifests/$file
	done
}

function create_k8s_system_namespace {

    $INSTALL_DIR/bin/kubectl create -f - << EOF > /dev/null 2>&1
kind: Namespace
apiVersion: v1
metadata:
  name: kube-system
  labels:
    name: kube-system
EOF
}

function start_kubelet {
	echo "INFO - Starting kubelet:$K8S_VERSION"

	$INSTALL_DIR/bin/kubelet \
        	--hostname-override=${K8S_HOSTNAME} \
		--address="0.0.0.0"  \
		--register-node=true \
		--api-servers=http://$K8S_HOSTNAME:${K8S_API_PORT} \
		--config=$INSTALL_DIR/etc/kubernetes/manifests \
		--cluster-dns=${K8S_DNS_IP} \
		--cluster-domain=cluster.local \
		--allow-privileged=true --v=2 \
		--root-dir="$INSTALL_DIR/kubelet" \
		--log-dir="$INSTALL_DIR/logs/" > $INSTALL_DIR/logs/kubelet.log 2>&1 &
	pidof kubelet > $INSTALL_DIR/run/kubelet.pid
}

function config_kubectl {
	$INSTALL_DIR/bin/kubectl config set-cluster qk8s --server=http://$K8S_HOSTNAME:8080
	$INSTALL_DIR/bin/kubectl config set-context qk8s --cluster=qk8s
	$INSTALL_DIR/bin/kubectl config use-context qk8s
}

function stop_kubelet {
	if [ -f $INSTALL_DIR/run/kubelet.pid ];then
		echo "INFO - Killing kubelet"
		kill -9 `cat $INSTALL_DIR/run/kubelet.pid`
		rm $INSTALL_DIR/run/kubelet.pid
	else
		echo "WARNING - kubelet PID file not found. Performing a killall. Hold on your pants"
		killall -9 kubelet
	fi
}
function stop_k8s_containers {

	k8s_containers=$(docker ps -aqf "name=k8s_")
	echo "INFO - Stopping k8s_ containers"
	if [ ! -z "$k8s_containers" ]; then
		docker stop $k8s_containers > /dev/null 2>&1
		docker wait $k8s_containers > /dev/null 2>&1
		docker rm -fv $k8s_containers > /dev/null 2>&1
	fi

}

function start_kubernetes {
	check_system
	download_kubelet
	copy_kubelet_manifests
	start_kubelet
	config_kubectl
	wait_for_kubernetes
	create_k8s_system_namespace
	echo "INFO - Started kubernetes version $K8S_VERSION"
	$INSTALL_DIR/bin/kubectl cluster-info

}

function stop_kubernetes {
	stop_kubelet
	stop_k8s_containers
}

function delete_kubelet {
	echo "INFO - Deleting kubelet binary"
	rm -rf $INSTALL_DIR/bin/kubelet
}

function umount_tokens {
	echo "INFO - Umounting tokens fs"
	for fs in `mount | grep "$INSTALL_DIR/kubelet/pods/" | awk '{print $3}'`; do
		umount $fs
	done
}

function delete_files {
	echo "INFO - Deleting POD files, logs, etc..."
	rm -rf $INSTALL_DIR/etc
	rm -rf $INSTALL_DIR/logs
	rm -rf $INSTALL_DIR/run
	rm -rf $INSTALL_DIR/kubelet
}

function delete_kubernetes {
	stop_kubelet
	stop_k8s_containers
	umount_tokens
	delete_kubelet
	delete_files
	echo "INFO - Kubernetes cluster deleted"
}

function addon_kubernetes {
	$INSTALL_DIR/bin/kubectl create -f addons
	$INSTALL_DIR/bin/kubectl cluster-info
}

function wait_for_kubernetes {
	echo "INFO - Waiting for kubernetes to become ready"
	until $($INSTALL_DIR/bin/kubectl cluster-info &> /dev/null); do
		sleep 1
	done
}

function print_usage {
    cat << EOF
qk8s is a utility for Quickly launching Kubernetes in Docker

Usage: qk8s [command]

Available commands:
  start		Quickly Starts Kubernetes in the Docker host currently configured with your local docker command
  stop		Stop Kubernetes cluster
  delete	Deletes and stops all Kubernetes cluster objects and containers
  addon		Creates addons from addon directory (DNS-addon, etc..)
  restart	Restart Kubernetes
EOF
}


if [ "$1" == "start" ]; then
	start_kubernetes
elif [ "$1" == "stop" ]; then
	stop_kubernetes
elif [ "$1" == "delete" ]; then
	delete_kubernetes
elif [ "$1" == "restart" ]; then
	qk8s down && qk8s up
elif [ "$1" == "addon" ]; then
	addon_kubernetes
else
	print_usage
fi
